// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package tutorial;

public final class PersonOuterClass {
  private PersonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string zipcode = 1;</code>
     * @return The zipcode.
     */
    java.lang.String getZipcode();
    /**
     * <code>string zipcode = 1;</code>
     * @return The bytes for zipcode.
     */
    com.google.protobuf.ByteString
        getZipcodeBytes();
  }
  /**
   * Protobuf type {@code tutorial.Address}
   */
  public static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Address)
      AddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      zipcode_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Address();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Address(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              zipcode_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tutorial.PersonOuterClass.internal_static_tutorial_Address_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tutorial.PersonOuterClass.internal_static_tutorial_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tutorial.PersonOuterClass.Address.class, tutorial.PersonOuterClass.Address.Builder.class);
    }

    public static final int ZIPCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object zipcode_;
    /**
     * <code>string zipcode = 1;</code>
     * @return The zipcode.
     */
    @java.lang.Override
    public java.lang.String getZipcode() {
      java.lang.Object ref = zipcode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zipcode_ = s;
        return s;
      }
    }
    /**
     * <code>string zipcode = 1;</code>
     * @return The bytes for zipcode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getZipcodeBytes() {
      java.lang.Object ref = zipcode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zipcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(zipcode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, zipcode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(zipcode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, zipcode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tutorial.PersonOuterClass.Address)) {
        return super.equals(obj);
      }
      tutorial.PersonOuterClass.Address other = (tutorial.PersonOuterClass.Address) obj;

      if (!getZipcode()
          .equals(other.getZipcode())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ZIPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getZipcode().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tutorial.PersonOuterClass.Address parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tutorial.PersonOuterClass.Address parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tutorial.PersonOuterClass.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tutorial.PersonOuterClass.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tutorial.PersonOuterClass.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tutorial.PersonOuterClass.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tutorial.PersonOuterClass.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tutorial.PersonOuterClass.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tutorial.PersonOuterClass.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tutorial.PersonOuterClass.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tutorial.PersonOuterClass.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tutorial.PersonOuterClass.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tutorial.PersonOuterClass.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Address)
        tutorial.PersonOuterClass.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tutorial.PersonOuterClass.internal_static_tutorial_Address_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tutorial.PersonOuterClass.internal_static_tutorial_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tutorial.PersonOuterClass.Address.class, tutorial.PersonOuterClass.Address.Builder.class);
      }

      // Construct using tutorial.PersonOuterClass.Address.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        zipcode_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tutorial.PersonOuterClass.internal_static_tutorial_Address_descriptor;
      }

      @java.lang.Override
      public tutorial.PersonOuterClass.Address getDefaultInstanceForType() {
        return tutorial.PersonOuterClass.Address.getDefaultInstance();
      }

      @java.lang.Override
      public tutorial.PersonOuterClass.Address build() {
        tutorial.PersonOuterClass.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tutorial.PersonOuterClass.Address buildPartial() {
        tutorial.PersonOuterClass.Address result = new tutorial.PersonOuterClass.Address(this);
        result.zipcode_ = zipcode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tutorial.PersonOuterClass.Address) {
          return mergeFrom((tutorial.PersonOuterClass.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tutorial.PersonOuterClass.Address other) {
        if (other == tutorial.PersonOuterClass.Address.getDefaultInstance()) return this;
        if (!other.getZipcode().isEmpty()) {
          zipcode_ = other.zipcode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tutorial.PersonOuterClass.Address parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tutorial.PersonOuterClass.Address) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object zipcode_ = "";
      /**
       * <code>string zipcode = 1;</code>
       * @return The zipcode.
       */
      public java.lang.String getZipcode() {
        java.lang.Object ref = zipcode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          zipcode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string zipcode = 1;</code>
       * @return The bytes for zipcode.
       */
      public com.google.protobuf.ByteString
          getZipcodeBytes() {
        java.lang.Object ref = zipcode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zipcode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string zipcode = 1;</code>
       * @param value The zipcode to set.
       * @return This builder for chaining.
       */
      public Builder setZipcode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        zipcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string zipcode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearZipcode() {
        
        zipcode_ = getDefaultInstance().getZipcode();
        onChanged();
        return this;
      }
      /**
       * <code>string zipcode = 1;</code>
       * @param value The bytes for zipcode to set.
       * @return This builder for chaining.
       */
      public Builder setZipcodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        zipcode_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Address)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Address)
    private static final tutorial.PersonOuterClass.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tutorial.PersonOuterClass.Address();
    }

    public static tutorial.PersonOuterClass.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      @java.lang.Override
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Address(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tutorial.PersonOuterClass.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CarsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Cars)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .tutorial.Cars.Car car = 1;</code>
     * @return Whether the car field is set.
     */
    boolean hasCar();
    /**
     * <code>optional .tutorial.Cars.Car car = 1;</code>
     * @return The enum numeric value on the wire for car.
     */
    int getCarValue();
    /**
     * <code>optional .tutorial.Cars.Car car = 1;</code>
     * @return The car.
     */
    tutorial.PersonOuterClass.Cars.Car getCar();
  }
  /**
   * Protobuf type {@code tutorial.Cars}
   */
  public static final class Cars extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Cars)
      CarsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Cars.newBuilder() to construct.
    private Cars(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Cars() {
      car_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Cars();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Cars(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
              bitField0_ |= 0x00000001;
              car_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tutorial.PersonOuterClass.internal_static_tutorial_Cars_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tutorial.PersonOuterClass.internal_static_tutorial_Cars_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tutorial.PersonOuterClass.Cars.class, tutorial.PersonOuterClass.Cars.Builder.class);
    }

    /**
     * Protobuf enum {@code tutorial.Cars.Car}
     */
    public enum Car
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FERRARI = 0;</code>
       */
      FERRARI(0),
      /**
       * <code>KIA = 1;</code>
       */
      KIA(1),
      /**
       * <code>FORD = 2;</code>
       */
      FORD(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FERRARI = 0;</code>
       */
      public static final int FERRARI_VALUE = 0;
      /**
       * <code>KIA = 1;</code>
       */
      public static final int KIA_VALUE = 1;
      /**
       * <code>FORD = 2;</code>
       */
      public static final int FORD_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Car valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Car forNumber(int value) {
        switch (value) {
          case 0: return FERRARI;
          case 1: return KIA;
          case 2: return FORD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Car>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Car> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Car>() {
              public Car findValueByNumber(int number) {
                return Car.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return tutorial.PersonOuterClass.Cars.getDescriptor().getEnumTypes().get(0);
      }

      private static final Car[] VALUES = values();

      public static Car valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Car(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tutorial.Cars.Car)
    }

    private int bitField0_;
    public static final int CAR_FIELD_NUMBER = 1;
    private int car_;
    /**
     * <code>optional .tutorial.Cars.Car car = 1;</code>
     * @return Whether the car field is set.
     */
    @java.lang.Override public boolean hasCar() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .tutorial.Cars.Car car = 1;</code>
     * @return The enum numeric value on the wire for car.
     */
    @java.lang.Override public int getCarValue() {
      return car_;
    }
    /**
     * <code>optional .tutorial.Cars.Car car = 1;</code>
     * @return The car.
     */
    @java.lang.Override public tutorial.PersonOuterClass.Cars.Car getCar() {
      @SuppressWarnings("deprecation")
      tutorial.PersonOuterClass.Cars.Car result = tutorial.PersonOuterClass.Cars.Car.valueOf(car_);
      return result == null ? tutorial.PersonOuterClass.Cars.Car.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, car_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, car_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tutorial.PersonOuterClass.Cars)) {
        return super.equals(obj);
      }
      tutorial.PersonOuterClass.Cars other = (tutorial.PersonOuterClass.Cars) obj;

      if (hasCar() != other.hasCar()) return false;
      if (hasCar()) {
        if (car_ != other.car_) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCar()) {
        hash = (37 * hash) + CAR_FIELD_NUMBER;
        hash = (53 * hash) + car_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tutorial.PersonOuterClass.Cars parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tutorial.PersonOuterClass.Cars parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tutorial.PersonOuterClass.Cars parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tutorial.PersonOuterClass.Cars parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tutorial.PersonOuterClass.Cars parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tutorial.PersonOuterClass.Cars parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tutorial.PersonOuterClass.Cars parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tutorial.PersonOuterClass.Cars parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tutorial.PersonOuterClass.Cars parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tutorial.PersonOuterClass.Cars parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tutorial.PersonOuterClass.Cars parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tutorial.PersonOuterClass.Cars parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tutorial.PersonOuterClass.Cars prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Cars}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Cars)
        tutorial.PersonOuterClass.CarsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tutorial.PersonOuterClass.internal_static_tutorial_Cars_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tutorial.PersonOuterClass.internal_static_tutorial_Cars_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tutorial.PersonOuterClass.Cars.class, tutorial.PersonOuterClass.Cars.Builder.class);
      }

      // Construct using tutorial.PersonOuterClass.Cars.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        car_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tutorial.PersonOuterClass.internal_static_tutorial_Cars_descriptor;
      }

      @java.lang.Override
      public tutorial.PersonOuterClass.Cars getDefaultInstanceForType() {
        return tutorial.PersonOuterClass.Cars.getDefaultInstance();
      }

      @java.lang.Override
      public tutorial.PersonOuterClass.Cars build() {
        tutorial.PersonOuterClass.Cars result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tutorial.PersonOuterClass.Cars buildPartial() {
        tutorial.PersonOuterClass.Cars result = new tutorial.PersonOuterClass.Cars(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.car_ = car_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tutorial.PersonOuterClass.Cars) {
          return mergeFrom((tutorial.PersonOuterClass.Cars)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tutorial.PersonOuterClass.Cars other) {
        if (other == tutorial.PersonOuterClass.Cars.getDefaultInstance()) return this;
        if (other.hasCar()) {
          setCar(other.getCar());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tutorial.PersonOuterClass.Cars parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tutorial.PersonOuterClass.Cars) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int car_ = 0;
      /**
       * <code>optional .tutorial.Cars.Car car = 1;</code>
       * @return Whether the car field is set.
       */
      @java.lang.Override public boolean hasCar() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .tutorial.Cars.Car car = 1;</code>
       * @return The enum numeric value on the wire for car.
       */
      @java.lang.Override public int getCarValue() {
        return car_;
      }
      /**
       * <code>optional .tutorial.Cars.Car car = 1;</code>
       * @param value The enum numeric value on the wire for car to set.
       * @return This builder for chaining.
       */
      public Builder setCarValue(int value) {
        bitField0_ |= 0x00000001;
        car_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .tutorial.Cars.Car car = 1;</code>
       * @return The car.
       */
      @java.lang.Override
      public tutorial.PersonOuterClass.Cars.Car getCar() {
        @SuppressWarnings("deprecation")
        tutorial.PersonOuterClass.Cars.Car result = tutorial.PersonOuterClass.Cars.Car.valueOf(car_);
        return result == null ? tutorial.PersonOuterClass.Cars.Car.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .tutorial.Cars.Car car = 1;</code>
       * @param value The car to set.
       * @return This builder for chaining.
       */
      public Builder setCar(tutorial.PersonOuterClass.Cars.Car value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        car_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .tutorial.Cars.Car car = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCar() {
        bitField0_ = (bitField0_ & ~0x00000001);
        car_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Cars)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Cars)
    private static final tutorial.PersonOuterClass.Cars DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tutorial.PersonOuterClass.Cars();
    }

    public static tutorial.PersonOuterClass.Cars getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Cars>
        PARSER = new com.google.protobuf.AbstractParser<Cars>() {
      @java.lang.Override
      public Cars parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cars(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Cars> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Cars> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tutorial.PersonOuterClass.Cars getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int64 age = 2;</code>
     * @return Whether the age field is set.
     */
    boolean hasAge();
    /**
     * <code>optional int64 age = 2;</code>
     * @return The age.
     */
    long getAge();

    /**
     * <code>.tutorial.Address address = 3;</code>
     * @return Whether the address field is set.
     */
    boolean hasAddress();
    /**
     * <code>.tutorial.Address address = 3;</code>
     * @return The address.
     */
    tutorial.PersonOuterClass.Address getAddress();
    /**
     * <code>.tutorial.Address address = 3;</code>
     */
    tutorial.PersonOuterClass.AddressOrBuilder getAddressOrBuilder();

    /**
     * <code>repeated .tutorial.Cars cars = 4;</code>
     */
    java.util.List<tutorial.PersonOuterClass.Cars> 
        getCarsList();
    /**
     * <code>repeated .tutorial.Cars cars = 4;</code>
     */
    tutorial.PersonOuterClass.Cars getCars(int index);
    /**
     * <code>repeated .tutorial.Cars cars = 4;</code>
     */
    int getCarsCount();
    /**
     * <code>repeated .tutorial.Cars cars = 4;</code>
     */
    java.util.List<? extends tutorial.PersonOuterClass.CarsOrBuilder> 
        getCarsOrBuilderList();
    /**
     * <code>repeated .tutorial.Cars cars = 4;</code>
     */
    tutorial.PersonOuterClass.CarsOrBuilder getCarsOrBuilder(
        int index);

    /**
     * <code>bool active = 5;</code>
     * @return The active.
     */
    boolean getActive();
  }
  /**
   * Protobuf type {@code tutorial.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      cars_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              age_ = input.readInt64();
              break;
            }
            case 26: {
              tutorial.PersonOuterClass.Address.Builder subBuilder = null;
              if (address_ != null) {
                subBuilder = address_.toBuilder();
              }
              address_ = input.readMessage(tutorial.PersonOuterClass.Address.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(address_);
                address_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                cars_ = new java.util.ArrayList<tutorial.PersonOuterClass.Cars>();
                mutable_bitField0_ |= 0x00000002;
              }
              cars_.add(
                  input.readMessage(tutorial.PersonOuterClass.Cars.parser(), extensionRegistry));
              break;
            }
            case 40: {

              active_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          cars_ = java.util.Collections.unmodifiableList(cars_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tutorial.PersonOuterClass.internal_static_tutorial_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tutorial.PersonOuterClass.internal_static_tutorial_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tutorial.PersonOuterClass.Person.class, tutorial.PersonOuterClass.Person.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private long age_;
    /**
     * <code>optional int64 age = 2;</code>
     * @return Whether the age field is set.
     */
    @java.lang.Override
    public boolean hasAge() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public long getAge() {
      return age_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private tutorial.PersonOuterClass.Address address_;
    /**
     * <code>.tutorial.Address address = 3;</code>
     * @return Whether the address field is set.
     */
    @java.lang.Override
    public boolean hasAddress() {
      return address_ != null;
    }
    /**
     * <code>.tutorial.Address address = 3;</code>
     * @return The address.
     */
    @java.lang.Override
    public tutorial.PersonOuterClass.Address getAddress() {
      return address_ == null ? tutorial.PersonOuterClass.Address.getDefaultInstance() : address_;
    }
    /**
     * <code>.tutorial.Address address = 3;</code>
     */
    @java.lang.Override
    public tutorial.PersonOuterClass.AddressOrBuilder getAddressOrBuilder() {
      return getAddress();
    }

    public static final int CARS_FIELD_NUMBER = 4;
    private java.util.List<tutorial.PersonOuterClass.Cars> cars_;
    /**
     * <code>repeated .tutorial.Cars cars = 4;</code>
     */
    @java.lang.Override
    public java.util.List<tutorial.PersonOuterClass.Cars> getCarsList() {
      return cars_;
    }
    /**
     * <code>repeated .tutorial.Cars cars = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends tutorial.PersonOuterClass.CarsOrBuilder> 
        getCarsOrBuilderList() {
      return cars_;
    }
    /**
     * <code>repeated .tutorial.Cars cars = 4;</code>
     */
    @java.lang.Override
    public int getCarsCount() {
      return cars_.size();
    }
    /**
     * <code>repeated .tutorial.Cars cars = 4;</code>
     */
    @java.lang.Override
    public tutorial.PersonOuterClass.Cars getCars(int index) {
      return cars_.get(index);
    }
    /**
     * <code>repeated .tutorial.Cars cars = 4;</code>
     */
    @java.lang.Override
    public tutorial.PersonOuterClass.CarsOrBuilder getCarsOrBuilder(
        int index) {
      return cars_.get(index);
    }

    public static final int ACTIVE_FIELD_NUMBER = 5;
    private boolean active_;
    /**
     * <code>bool active = 5;</code>
     * @return The active.
     */
    @java.lang.Override
    public boolean getActive() {
      return active_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(2, age_);
      }
      if (address_ != null) {
        output.writeMessage(3, getAddress());
      }
      for (int i = 0; i < cars_.size(); i++) {
        output.writeMessage(4, cars_.get(i));
      }
      if (active_ != false) {
        output.writeBool(5, active_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, age_);
      }
      if (address_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getAddress());
      }
      for (int i = 0; i < cars_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, cars_.get(i));
      }
      if (active_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, active_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tutorial.PersonOuterClass.Person)) {
        return super.equals(obj);
      }
      tutorial.PersonOuterClass.Person other = (tutorial.PersonOuterClass.Person) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!getCarsList()
          .equals(other.getCarsList())) return false;
      if (getActive()
          != other.getActive()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAge());
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      if (getCarsCount() > 0) {
        hash = (37 * hash) + CARS_FIELD_NUMBER;
        hash = (53 * hash) + getCarsList().hashCode();
      }
      hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getActive());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tutorial.PersonOuterClass.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tutorial.PersonOuterClass.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tutorial.PersonOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tutorial.PersonOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tutorial.PersonOuterClass.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tutorial.PersonOuterClass.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tutorial.PersonOuterClass.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tutorial.PersonOuterClass.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tutorial.PersonOuterClass.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tutorial.PersonOuterClass.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tutorial.PersonOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tutorial.PersonOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tutorial.PersonOuterClass.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Person)
        tutorial.PersonOuterClass.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tutorial.PersonOuterClass.internal_static_tutorial_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tutorial.PersonOuterClass.internal_static_tutorial_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tutorial.PersonOuterClass.Person.class, tutorial.PersonOuterClass.Person.Builder.class);
      }

      // Construct using tutorial.PersonOuterClass.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCarsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (addressBuilder_ == null) {
          address_ = null;
        } else {
          address_ = null;
          addressBuilder_ = null;
        }
        if (carsBuilder_ == null) {
          cars_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          carsBuilder_.clear();
        }
        active_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tutorial.PersonOuterClass.internal_static_tutorial_Person_descriptor;
      }

      @java.lang.Override
      public tutorial.PersonOuterClass.Person getDefaultInstanceForType() {
        return tutorial.PersonOuterClass.Person.getDefaultInstance();
      }

      @java.lang.Override
      public tutorial.PersonOuterClass.Person build() {
        tutorial.PersonOuterClass.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public tutorial.PersonOuterClass.Person buildPartial() {
        tutorial.PersonOuterClass.Person result = new tutorial.PersonOuterClass.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000001;
        }
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        if (carsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            cars_ = java.util.Collections.unmodifiableList(cars_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.cars_ = cars_;
        } else {
          result.cars_ = carsBuilder_.build();
        }
        result.active_ = active_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tutorial.PersonOuterClass.Person) {
          return mergeFrom((tutorial.PersonOuterClass.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tutorial.PersonOuterClass.Person other) {
        if (other == tutorial.PersonOuterClass.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        if (carsBuilder_ == null) {
          if (!other.cars_.isEmpty()) {
            if (cars_.isEmpty()) {
              cars_ = other.cars_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureCarsIsMutable();
              cars_.addAll(other.cars_);
            }
            onChanged();
          }
        } else {
          if (!other.cars_.isEmpty()) {
            if (carsBuilder_.isEmpty()) {
              carsBuilder_.dispose();
              carsBuilder_ = null;
              cars_ = other.cars_;
              bitField0_ = (bitField0_ & ~0x00000002);
              carsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCarsFieldBuilder() : null;
            } else {
              carsBuilder_.addAllMessages(other.cars_);
            }
          }
        }
        if (other.getActive() != false) {
          setActive(other.getActive());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tutorial.PersonOuterClass.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tutorial.PersonOuterClass.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private long age_ ;
      /**
       * <code>optional int64 age = 2;</code>
       * @return Whether the age field is set.
       */
      @java.lang.Override
      public boolean hasAge() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int64 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public long getAge() {
        return age_;
      }
      /**
       * <code>optional int64 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(long value) {
        bitField0_ |= 0x00000001;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0L;
        onChanged();
        return this;
      }

      private tutorial.PersonOuterClass.Address address_;
      private com.google.protobuf.SingleFieldBuilderV3<
          tutorial.PersonOuterClass.Address, tutorial.PersonOuterClass.Address.Builder, tutorial.PersonOuterClass.AddressOrBuilder> addressBuilder_;
      /**
       * <code>.tutorial.Address address = 3;</code>
       * @return Whether the address field is set.
       */
      public boolean hasAddress() {
        return addressBuilder_ != null || address_ != null;
      }
      /**
       * <code>.tutorial.Address address = 3;</code>
       * @return The address.
       */
      public tutorial.PersonOuterClass.Address getAddress() {
        if (addressBuilder_ == null) {
          return address_ == null ? tutorial.PersonOuterClass.Address.getDefaultInstance() : address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>.tutorial.Address address = 3;</code>
       */
      public Builder setAddress(tutorial.PersonOuterClass.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
          onChanged();
        } else {
          addressBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tutorial.Address address = 3;</code>
       */
      public Builder setAddress(
          tutorial.PersonOuterClass.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
          onChanged();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tutorial.Address address = 3;</code>
       */
      public Builder mergeAddress(tutorial.PersonOuterClass.Address value) {
        if (addressBuilder_ == null) {
          if (address_ != null) {
            address_ =
              tutorial.PersonOuterClass.Address.newBuilder(address_).mergeFrom(value).buildPartial();
          } else {
            address_ = value;
          }
          onChanged();
        } else {
          addressBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tutorial.Address address = 3;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = null;
          onChanged();
        } else {
          address_ = null;
          addressBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tutorial.Address address = 3;</code>
       */
      public tutorial.PersonOuterClass.Address.Builder getAddressBuilder() {
        
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>.tutorial.Address address = 3;</code>
       */
      public tutorial.PersonOuterClass.AddressOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_ == null ?
              tutorial.PersonOuterClass.Address.getDefaultInstance() : address_;
        }
      }
      /**
       * <code>.tutorial.Address address = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          tutorial.PersonOuterClass.Address, tutorial.PersonOuterClass.Address.Builder, tutorial.PersonOuterClass.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              tutorial.PersonOuterClass.Address, tutorial.PersonOuterClass.Address.Builder, tutorial.PersonOuterClass.AddressOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }

      private java.util.List<tutorial.PersonOuterClass.Cars> cars_ =
        java.util.Collections.emptyList();
      private void ensureCarsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          cars_ = new java.util.ArrayList<tutorial.PersonOuterClass.Cars>(cars_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          tutorial.PersonOuterClass.Cars, tutorial.PersonOuterClass.Cars.Builder, tutorial.PersonOuterClass.CarsOrBuilder> carsBuilder_;

      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public java.util.List<tutorial.PersonOuterClass.Cars> getCarsList() {
        if (carsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cars_);
        } else {
          return carsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public int getCarsCount() {
        if (carsBuilder_ == null) {
          return cars_.size();
        } else {
          return carsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public tutorial.PersonOuterClass.Cars getCars(int index) {
        if (carsBuilder_ == null) {
          return cars_.get(index);
        } else {
          return carsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public Builder setCars(
          int index, tutorial.PersonOuterClass.Cars value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.set(index, value);
          onChanged();
        } else {
          carsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public Builder setCars(
          int index, tutorial.PersonOuterClass.Cars.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.set(index, builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public Builder addCars(tutorial.PersonOuterClass.Cars value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.add(value);
          onChanged();
        } else {
          carsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public Builder addCars(
          int index, tutorial.PersonOuterClass.Cars value) {
        if (carsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarsIsMutable();
          cars_.add(index, value);
          onChanged();
        } else {
          carsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public Builder addCars(
          tutorial.PersonOuterClass.Cars.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.add(builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public Builder addCars(
          int index, tutorial.PersonOuterClass.Cars.Builder builderForValue) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.add(index, builderForValue.build());
          onChanged();
        } else {
          carsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public Builder addAllCars(
          java.lang.Iterable<? extends tutorial.PersonOuterClass.Cars> values) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cars_);
          onChanged();
        } else {
          carsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public Builder clearCars() {
        if (carsBuilder_ == null) {
          cars_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          carsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public Builder removeCars(int index) {
        if (carsBuilder_ == null) {
          ensureCarsIsMutable();
          cars_.remove(index);
          onChanged();
        } else {
          carsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public tutorial.PersonOuterClass.Cars.Builder getCarsBuilder(
          int index) {
        return getCarsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public tutorial.PersonOuterClass.CarsOrBuilder getCarsOrBuilder(
          int index) {
        if (carsBuilder_ == null) {
          return cars_.get(index);  } else {
          return carsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public java.util.List<? extends tutorial.PersonOuterClass.CarsOrBuilder> 
           getCarsOrBuilderList() {
        if (carsBuilder_ != null) {
          return carsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cars_);
        }
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public tutorial.PersonOuterClass.Cars.Builder addCarsBuilder() {
        return getCarsFieldBuilder().addBuilder(
            tutorial.PersonOuterClass.Cars.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public tutorial.PersonOuterClass.Cars.Builder addCarsBuilder(
          int index) {
        return getCarsFieldBuilder().addBuilder(
            index, tutorial.PersonOuterClass.Cars.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Cars cars = 4;</code>
       */
      public java.util.List<tutorial.PersonOuterClass.Cars.Builder> 
           getCarsBuilderList() {
        return getCarsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          tutorial.PersonOuterClass.Cars, tutorial.PersonOuterClass.Cars.Builder, tutorial.PersonOuterClass.CarsOrBuilder> 
          getCarsFieldBuilder() {
        if (carsBuilder_ == null) {
          carsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              tutorial.PersonOuterClass.Cars, tutorial.PersonOuterClass.Cars.Builder, tutorial.PersonOuterClass.CarsOrBuilder>(
                  cars_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          cars_ = null;
        }
        return carsBuilder_;
      }

      private boolean active_ ;
      /**
       * <code>bool active = 5;</code>
       * @return The active.
       */
      @java.lang.Override
      public boolean getActive() {
        return active_;
      }
      /**
       * <code>bool active = 5;</code>
       * @param value The active to set.
       * @return This builder for chaining.
       */
      public Builder setActive(boolean value) {
        
        active_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool active = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearActive() {
        
        active_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Person)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Person)
    private static final tutorial.PersonOuterClass.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tutorial.PersonOuterClass.Person();
    }

    public static tutorial.PersonOuterClass.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public tutorial.PersonOuterClass.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Address_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Cars_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Cars_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\010tutorial\"\032\n\007Address\022\017\n\007z" +
      "ipcode\030\001 \001(\t\"[\n\004Cars\022$\n\003car\030\001 \001(\0162\022.tuto" +
      "rial.Cars.CarH\000\210\001\001\"%\n\003Car\022\013\n\007FERRARI\020\000\022\007" +
      "\n\003KIA\020\001\022\010\n\004FORD\020\002B\006\n\004_car\"\214\001\n\006Person\022\014\n\004" +
      "name\030\001 \001(\t\022\020\n\003age\030\002 \001(\003H\000\210\001\001\022\"\n\007address\030" +
      "\003 \001(\0132\021.tutorial.Address\022\034\n\004cars\030\004 \003(\0132\016" +
      ".tutorial.Cars\022\016\n\006active\030\005 \001(\010B\006\n\004_ageR\003" +
      "fooR\003barb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Address_descriptor,
        new java.lang.String[] { "Zipcode", });
    internal_static_tutorial_Cars_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_Cars_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Cars_descriptor,
        new java.lang.String[] { "Car", "Car", });
    internal_static_tutorial_Person_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tutorial_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Person_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", "Cars", "Active", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
